#pragma once
#define _USE_MATH_DEFINES
//Godot headers
#include <Godot.hpp>
#include <KinematicBody2D.hpp>
#include <StaticBody2D.hpp>
#include <Area2D.hpp>
#include <Sprite.hpp>
#include <Camera2D.hpp>
#include <Node.hpp>
#include <File.hpp>
#include <JSON.hpp>
#include <JSONParseResult.hpp>
#include <CanvasLayer.hpp>
#include <Button.hpp>
#include <SceneTree.hpp>
#include <Control.hpp>
#include <Texture.hpp>

#include <Position2D.hpp>
#include <Input.hpp>
#include <AnimatedSprite.hpp>
#include <AnimationPlayer.hpp>
#include <AnimationTree.hpp>
#include <AnimationNodeStateMachinePlayback.hpp>
#include <ResourceLoader.hpp>
#include <ResourceLoader.hpp>
#include <PackedScene.hpp>
#include <Timer.hpp>
#include <Label.hpp>
#include <TextureButton.hpp>
#include <Array.hpp>
#include<RandomNumberGenerator.hpp>
//My headers
#include "Player.h"
#include "Grass.h"
#include "BatAI.h"
#include "CameraController.h"
#include "Coin.h"
#include "UI.h"
#include "Loader.h"
#include "Bullet.h"
#include "Acorn.h"
#include "PauseButton.h"
#include "ContinueButton.h"
#include "HealthUI.h"
#include "RestartButton.h"
#include "QuitButton.h"
#include "LoadSceneButton.h"
#include "Tomb.h"
#include "CheckPoint.h"
#include "Countryman.h"
#include "StoreButton.h"
#include "Backpack.h"
#include "Meat.h"
#include "BoarAI.h"

//cpp headers
#include <cmath>
#include <string>